# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example

  # Uncomment lines below to enable adminer
  # adminer:
  #   build: .
  #   image: adminer_ld
  #   restart: always
  #   ports:
  #     - 8080:8080